using FluentAssertions;
using ScaffoldX.App.Services;
using Xunit;

namespace ScaffoldX.App.Tests.Services;

/// <summary>
/// ScribanTemplateEngine 单元测试：验证 .resx 模板渲染后包含正确的资源键。
/// </summary>
public class ScribanTemplateEngineResxTests
{
    private readonly ScribanTemplateEngine _sut = new();

    /// <summary>
    /// 验证渲染 .resx 模板后，XML 包含 WelcomeText、RunningStatus 等资源键。
    /// </summary>
    [Fact]
    public void Render_ResxTemplate_ShouldContainResourceKeys()
    {
        // Arrange
        var resxTemplate = @"<?xml version=""1.0"" encoding=""utf-8""?>
<root>
  <data name=""WelcomeText"" xml:space=""preserve"">
    <value>Welcome to {{ ProjectName }}</value>
  </data>
  <data name=""RunningStatus"" xml:space=""preserve"">
    <value>Running Status</value>
  </data>
  <data name=""PluginCount"" xml:space=""preserve"">
    <value>Loaded Plugins</value>
  </data>
  <data name=""AlarmCount"" xml:space=""preserve"">
    <value>Today's Alarms</value>
  </data>
  <data name=""FooterText"" xml:space=""preserve"">
    <value>{{ ProjectName }} — Generated by ScaffoldX {{ ScaffoldXVersion }}</value>
  </data>
  <data name=""ConnectionStatus"" xml:space=""preserve"">
    <value>Connection Status</value>
  </data>
  <data name=""Disconnected"" xml:space=""preserve"">
    <value>Disconnected</value>
  </data>
  <data name=""CurrentUser"" xml:space=""preserve"">
    <value>Current User</value>
  </data>
  <data name=""HomePage"" xml:space=""preserve"">
    <value>Home</value>
  </data>
  <data name=""LogViewer"" xml:space=""preserve"">
    <value>Log Viewer</value>
  </data>
  <data name=""PluginStatus"" xml:space=""preserve"">
    <value>Plugin Status</value>
  </data>
  <data name=""LanguageLabel"" xml:space=""preserve"">
    <value>Language</value>
  </data>
  <data name=""ThemeLabel"" xml:space=""preserve"">
    <value>Theme</value>
  </data>
</root>";

        var variables = new Dictionary<string, object>
        {
            ["ProjectName"] = "MyApp",
            ["ScaffoldXVersion"] = "1.0.0"
        };

        // Act
        var result = _sut.Render(resxTemplate, variables);

        // Assert
        result.Should().Contain("name=\"WelcomeText\"");
        result.Should().Contain("name=\"RunningStatus\"");
        result.Should().Contain("name=\"PluginCount\"");
        result.Should().Contain("name=\"AlarmCount\"");
        result.Should().Contain("name=\"FooterText\"");
        result.Should().Contain("name=\"ConnectionStatus\"");
        result.Should().Contain("name=\"Disconnected\"");
        result.Should().Contain("name=\"CurrentUser\"");
        result.Should().Contain("name=\"HomePage\"");
        result.Should().Contain("name=\"LogViewer\"");
        result.Should().Contain("name=\"PluginStatus\"");
        result.Should().Contain("name=\"LanguageLabel\"");
        result.Should().Contain("name=\"ThemeLabel\"");
        result.Should().Contain("Welcome to MyApp",
            "ProjectName 变量应被正确替换");
    }
}
